name: Build GKI Kernel with KernelSU + SUSFS4KSU

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Setup build environment
      run: |
        sudo apt-get update -qq
        sudo apt-get install -y --no-install-recommends \
          build-essential bc bison flex git-core curl \
          python3 python3-dev libssl-dev cpio rsync \
          zip unzip
        
    - name: Setup repo tool
      run: |
        mkdir -p ~/.local/bin
        curl -fsSL https://storage.googleapis.com/git-repo-downloads/repo -o ~/.local/bin/repo
        chmod +x ~/.local/bin/repo
        echo "$HOME/.local/bin" >> $GITHUB_PATH
        
    - name: Configure git
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        
    - name: Create workspace and get build info
      run: |
        BUILD_DATE=$(date +"%Y%m%d")
        BUILD_TIME=$(date +"%H%M")
        KERNEL_NAME="kyernel-${BUILD_DATE}-${BUILD_TIME}"
        echo "BUILD_DATE_FORMATTED=$(date +"%Y-%m-%d")" >> $GITHUB_ENV
        echo "BUILD_TIME_FORMATTED=$(date +"%H:%M")" >> $GITHUB_ENV
        echo "KERNEL_NAME=${KERNEL_NAME}" >> $GITHUB_ENV
        
    - name: Clone kernel source
      run: |
        mkdir android-kernel && cd android-kernel
        repo init -u https://android.googlesource.com/kernel/manifest \
          -b common-android14-6.1-2025-06 --depth=1 --no-clone-bundle
        repo sync -c -j$(nproc) --no-tags --optimized-fetch
        
    - name: Setup KernelSU
      run: |
        cd android-kernel
        
        # Setup KernelSU
        curl -fsSL "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -s main
        
        # Get KSU version
        cd KernelSU
        BASE_VERSION=10200
        COMMIT_COUNT=$(git rev-list --count HEAD)
        KSU_VERSION=$((COMMIT_COUNT + BASE_VERSION))
        echo "KSU_GIT_VERSION=$KSU_VERSION" >> $GITHUB_ENV
        echo "KernelSU version: $KSU_VERSION"
        cd .
        export KSU_GIT_VERSION="$KSU_VERSION"
        
    - name: Clone repositories
      run: |
        cd android-kernel
        
        # Clone SUSFS
        git clone --depth=1 https://gitlab.com/simonpunk/susfs4ksu.git -b gki-android14-6.1 susfs4ksu
        
        # Clone hooks patches
        git clone --depth=1 https://github.com/enskye/kernel_patches.git -b main kernel_patches

        # Clone AnyKernel3
        git clone --depth=1 https://github.com/enskye/AnyKernel3.git -b gki-2.0 AnyKernel3
        
        # Apply SUSFS patches
        cp susfs4ksu/kernel_patches/fs/* ./common/fs/
        cp susfs4ksu/kernel_patches/include/linux/* ./common/include/linux/
        cp susfs4ksu/kernel_patches/KernelSU/10_enable_susfs_for_ksu.patch KernelSU/
        cp susfs4ksu/kernel_patches/50_add_susfs_in_gki-android14-6.1.patch ./common/
        cp kernel_patches/hooks/60_scope_minimized_hooks_ksu_1.4.patch ./common/
        # cp kernel_patches/prctl.patch ./common/
        cd KernelSU
        patch -p1 --fuzz=3 < 10_enable_susfs_for_ksu.patch
        cd ../common
        patch -p1 --fuzz=3 < 50_add_susfs_in_gki-android14-6.1.patch
        patch -p1 --fuzz=3 < 60_scope_minimized_hooks_ksu_1.4.patch
        # patch -p1 --fuzz=3 < prctl.patch
        
    - name: Configure kernel options
      run: |
        cd android-kernel/common/arch/arm64/configs
        echo "CONFIG_KSU=y" >> gki_defconfig
        echo "CONFIG_KSU_SUSFS=y" >> gki_defconfig
        echo "CONFIG_KSU_SUSFS_HAS_MAGIC_MOUNT=n" >> gki_defconfig
        echo "CONFIG_KSU_SUSFS_SUS_PATH=y" >> gki_defconfig
        echo "CONFIG_KSU_SUSFS_SUS_MOUNT=y" >> gki_defconfig
        echo "CONFIG_KSU_SUSFS_AUTO_ADD_SUS_KSU_DEFAULT_MOUNT=y" >> gki_defconfig
        echo "CONFIG_KSU_SUSFS_AUTO_ADD_SUS_BIND_MOUNT=y" >> gki_defconfig
        echo "CONFIG_KSU_SUSFS_SUS_KSTAT=y" >> gki_defconfig
        echo "CONFIG_KSU_SUSFS_SUS_OVERLAYFS=y" >> gki_defconfig
        echo "CONFIG_KSU_SUSFS_TRY_UMOUNT=y" >> gki_defconfig
        echo "CONFIG_KSU_USFS_AUTO_ADD_TRY_UMOUNT_FOR_BIND_MOUNT=y" >> gki_defconfig
        echo "CONFIG_KSU_SUSFS_SPOOF_UNAME=y" >> gki_defconfig
        echo "CONFIG_KSU_SUSFS_ENABLE_LOG=y" >> gki_defconfig
        echo "CONFIG_KSU_SUSFS_HIDE_KSU_SUSFS_SYMBOLS=y" >> gki_defconfig
        echo "CONFIG_KSU_SUSFS_SPOOF_CMDLINE_OR_BOOTCONFIG=y" >> gki_defconfig
        echo "CONFIG_KSU_SUSFS_OPEN_REDIRECT=y" >> gki_defconfig
        echo "CONFIG_KSU_SUSFS_SUS_SU=n" >> gki_defconfig
        echo "CONFIG_KSU_KPROBES_HOOK=n" >> gki_defconfig

    - name: Modify uname
      run: |
        cd android-kernel
        echo 'echo "-kyernel"' > ./common/scripts/setlocalversion
        
    - name: Build kernel
      run: |
        cd android-kernel
        
        # Remove ABI dependencies just before building
        sed -i '/protected_exports_list.*abi_gki_protected_exports_aarch64/d' common/BUILD.bazel
        rm -f common/android/abi_gki_protected_exports_*
        sed -i 's/check_defconfig//' common/build.config.gki
        
        
        # Use the kernel's built-in bazel wrapper (tools/bazel)
        tools/bazel run //common:kernel_aarch64_dist --config=fast --config=stamp --lto=thin -- --destdir=out/dist

    - name: Prepare kernel image
      run: |
        cd android-kernel/out/dist
        
        if [[ -f "Image" ]]; then
          lz4 -9 -f Image Image.lz4
          KERNEL_IMAGE="Image.lz4"
        elif [[ -f "Image.gz" ]]; then
          gunzip Image.gz
          lz4 -9 -f Image Image.lz4
          KERNEL_IMAGE="Image.lz4"
        else
          echo "❌ No kernel image found!"
          exit 1
        fi
        
        echo "KERNEL_IMAGE=${KERNEL_IMAGE}" >> $GITHUB_ENV

    - name: Create AnyKernel3 package
      run: |
        cd android-kernel/out/dist
        cp ../android-kernel/out/dist/Image.lz4 .
        ZIP_NAME="${KERNEL_NAME}.zip"
        zip -r9 "../$ZIP_NAME" . -x "*.git*" "README.md" "LICENSE"

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ env.KERNEL_NAME }}
        name: ${{ env.KERNEL_NAME }}
        body: |
          ## 🚀 GKI2 Build - ${{ env.KERNEL_NAME }}
          
          **Build Information:**
          - **Build Date**: ${{ env.BUILD_DATE_FORMATTED }}
          - **Build Time**: ${{ env.BUILD_TIME_FORMATTED }} UTC
          
          **Components:**
          - ✅ KernelSU;
          - ✅ SUSFS;
          - ✅ AnyKernel3.
              
          **Note**: This kernel includes KernelSU-Next with SUSFS for enhanced root hiding capabilities.
        files: |
          android-kernel/out/dist/${{ env.KERNEL_NAME }}.zip
        draft: false
        prerelease: false
               
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: kernel-build
        path: android-kernel/out/dist/*
