name: Build GKI Kernel with KernelSU + SUSFS4KSU

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Setup build environment
      run: |
        sudo apt-get update -qq
        sudo apt-get install -y --no-install-recommends \
          build-essential bc bison flex git-core curl \
          python3 python3-dev libssl-dev cpio rsync \
          zip unzip
        
    - name: Setup repo and clone kernel
      run: |
        # Setup repo tool
        mkdir -p ~/.local/bin
        curl -fsSL https://storage.googleapis.com/git-repo-downloads/repo -o ~/.local/bin/repo
        chmod +x ~/.local/bin/repo
        echo "$HOME/.local/bin" >> $GITHUB_PATH
        
        # Configure git (required for repo)
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        
        # Clone kernel with optimized settings
        mkdir android-kernel && cd android-kernel
        ~/.local/bin/repo init -u https://android.googlesource.com/kernel/manifest \
          -b common-android14-6.1-lts --depth=1 --no-clone-bundle
        ~/.local/bin/repo sync -c -j$(nproc) --no-tags --optimized-fetch
        
    - name: Setup KernelSU and SUSFS
      run: |
        cd android-kernel
        
        # Setup KernelSU
        curl -fsSL "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -s main
        
        # Get KSU version (official git describe method)
        cd KernelSU
        # Method 1: Try git describe (most reliable)
        KSU_VERSION=$(git describe --always --tags --dirty 2>/dev/null || echo "")
        
        # Method 2: Fallback to commit count if no tags
        if [[ -z "$KSU_VERSION" || "$KSU_VERSION" == *"fatal"* ]]; then
          BASE_VERSION=10200
          COMMIT_COUNT=$(git rev-list --count HEAD)
          KSU_VERSION=$((COMMIT_COUNT + BASE_VERSION))
        fi
        
        echo "KSUVER=$KSU_VERSION" >> $GITHUB_ENV
        echo "KernelSU version: $KSU_VERSION"
        cd ..
        
        # Clone SUSFS
        git clone --depth=1 https://gitlab.com/simonpunk/susfs4ksu.git -b gki-android14-6.1 susfs4ksu
        
    - name: Apply SUSFS patches
      run: |
        cd android-kernel
        
        # Apply SUSFS patches - simplified
        cp susfs4ksu/kernel_patches/KernelSU/10_enable_susfs_for_ksu.patch KernelSU/
        cd KernelSU
        patch -p1 < 10_enable_susfs_for_ksu.patch
        cd ../common
        patch -p1 < ../susfs4ksu/kernel_patches/50_add_susfs_in_gki-android14-6.1.patch
        
        
    - name: Configure kernel options
      run: |
        cd android-kernel/common/arch/arm64/configs
        echo "CONFIG_KSU=y" >> gki_defconfig
        echo "CONFIG_KSU_SUSFS=y" >> gki_defconfig
        echo "CONFIG_KSU_SUSFS_HAS_MAGIC_MOUNT=n" >> gki_defconfig
        echo "CONFIG_KSU_SUSFS_SUS_PATH=y" >> gki_defconfig
        echo "CONFIG_KSU_SUSFS_SUS_MOUNT=y" >> gki_defconfig
        echo "CONFIG_KSU_SUSFS_AUTO_ADD_SUS_KSU_DEFAULT_MOUNT=y" >> gki_defconfig
        echo "CONFIG_KSU_SUSFS_AUTO_ADD_SUS_BIND_MOUNT=y" >> gki_defconfig
        echo "CONFIG_KSU_SUSFS_SUS_KSTAT=y" >> gki_defconfig
        echo "CONFIG_KSU_SUSFS_SUS_OVERLAYFS=n" >> gki_defconfig
        echo "CONFIG_KSU_SUSFS_TRY_UMOUNT=y" >> gki_defconfig
        echo "CONFIG_KSU_SUSFS_AUTO_ADD_TRY_UMOUNT_FOR_BIND_MOUNT=y" >> gki_defconfig
        echo "CONFIG_KSU_SUSFS_SPOOF_UNAME=y" >> gki_defconfig
        echo "CONFIG_KSU_SUSFS_ENABLE_LOG=y" >> gki_defconfig
        echo "CONFIG_KSU_SUSFS_HIDE_KSU_SUSFS_SYMBOLS=y" >> gki_defconfig
        echo "CONFIG_KSU_SUSFS_SPOOF_CMDLINE_OR_BOOTCONFIG=y" >> gki_defconfig
        echo "CONFIG_KSU_SUSFS_OPEN_REDIRECT=y" >> gki_defconfig
        echo "CONFIG_KSU_SUSFS_SUS_SU=y" >> gki_defconfig
        
    - name: Build kernel
      run: |
        cd android-kernel
        
        # Remove ABI dependencies just before building
        sed -i '/protected_exports_list.*abi_gki_protected_exports_aarch64/d' common/BUILD.bazel
        rm -f common/android/abi_gki_protected_exports_*
        sed -i 's/check_defconfig//' common/build.config.gki
        
        # Set KernelSU version for build
        export KSU_GIT_VERSION="${{ env.KSUVER }}"
        
        # Use the kernel's built-in bazel wrapper (tools/bazel)
        tools/bazel build //common:kernel_aarch64_dist
               
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: kernel-build-${{ github.run_number }}
        path: |
          android-kernel/bazel-bin/common/kernel_aarch64_dist/**
        retention-days: 7
