name: Build GKI Kernel with KernelSU + SUSFS

on:
  workflow_dispatch:

env:
  KERNEL_ROOT: ${{ github.workspace }}/kernel_src
  DIST_DIR: ${{ github.workspace }}/dist
  DEFCONFIG: gki_defconfig

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential bc bison flex libssl-dev \
            libncurses5-dev curl git ccache python3 unzip zip perl

      - name: Clone kernel source
        run: |
          git clone --depth=1 https://android.googlesource.com/kernel/common $KERNEL_ROOT

      - name: Integrate KernelSU + SUSFS
        run: |
          cd $KERNEL_ROOT/common/drivers
          rm -rf kernelsu susfs
          git clone --depth=1 https://github.com/tiann/kernelsu.git
          git clone --depth=1 https://github.com/tiann/susfs4ksu.git susfs

      - name: Configure defconfig & patch
        run: |
          cd $KERNEL_ROOT
          make ARCH=arm64 O=out mrproper
          make ARCH=arm64 O=out ${DEFCONFIG}

          # Remove ABI protected exports & strict enforcement
          rm -rf ./common/android/abi_gki_protected_exports_*
          perl -pi -e 's/^\s*"protected_exports_list"\s*:\s*"android\/abi_gki_protected_exports_aarch64",\s*$//;' ./common/BUILD.bazel

          # Remove check_defconfig
          sed -i 's/check_defconfig//' ./common/build.config.gki

          # Enable KSU + SUSFS configs automatically
          cd common
          ./scripts/config --file arch/arm64/configs/${DEFCONFIG} --enable CONFIG_KSU
          ./scripts/config --file arch/arm64/configs/${DEFCONFIG} --enable CONFIG_KSU_SUSFS
          make ARCH=arm64 savedefconfig
          cp defconfig arch/arm64/configs/${DEFCONFIG}
          cd ..

      - name: Build kernel
        run: |
          cd $KERNEL_ROOT
          tools/bazel build //common:kernel_aarch64_dist

      - name: Package with AnyKernel3
        run: |
          git clone --depth=1 https://github.com/enskye/AnyKernel3
          cp $KERNEL_ROOT/bazel-bin/common/kernel_aarch64/Image AnyKernel3/
          cp $KERNEL_ROOT/bazel-bin/common/kernel_aarch64/*.ko AnyKernel3/ || true
          cd AnyKernel3
          zip -r9 ${{ github.workspace }}/KernelSU-SUSFS.zip *

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: KernelSU-SUSFS
          path: KernelSU-SUSFS.zip
